author:
  name: Jakub "Jorengarenar" ≈Åukasiewicz

title: Joren
description: Programming? Programming!

baseurl: /blog

remote_theme: jekyll/minima

show_excerpts: true

permalink: /:categories/:title

minima:
  date_format: "%F"
  social_links:
    devto:         Jorengarenar
    github:        Jorengarenar
    instagram:     Jorengarenar
    linkedin:      jakub-lukasiewicz
    stackoverflow: "10247460"
    twitter:       Jorengarenar

disqus:
  shortname: jorengarenar

header_pages:
  - pages/categories.html
  - pages/tags.html

header_external_links:
  - title: Home
    url:   https://joren.ga

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
